name: Webserv compilation and Siege test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Build
        run: |
          make

      - name: Install Siege
        run: |
          sudo apt-get install -y siege

      - name: Run Server
        run: |
          nohup bin/webserv > server_log.txt 2>&1 &
          sleep 1
      - name: Run Siege Test
        run: |
          siege -c 10 -t 2M http://127.0.0.1:8000 > siege_output.txt

      - name: Stop Server
        run: |
          pkill webserv

      - name: Save Siege Output as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: siege_output
          path: siege_output.txt
